name: personal
recipe: lamp
config:
  php: '7.4'
  webroot: ./web/
  composer_version: '2.1.3'
  database: mysql:5.7
  xdebug: 'debug,coverage'
  config:
    server: ./.lando/
    php: ./.lando/php/php.ini
services:
  pma:
    type: 'phpmyadmin:5.0'
    hosts:
      - database
  node:
    type: node
    globals:
      gulp-cli: latest
tooling:
  node:
    service: node
  npm:
    service: node
  yarn:
    service: node
  gulp:
    service: node
proxy:
  pma:
    - pma.personal.lndo.site